# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Dependencias de Maven (Java / Spring Boot)
  - package-ecosystem: "maven"
    directory: "/" # raíz del proyecto, donde está pom.xml
    schedule:
      interval: "weekly"

  # Dependencias de Dockerfile
  - package-ecosystem: "docker"
    directory: "/" # raíz, si tu Dockerfile está ahí
    schedule:
      interval: "weekly"

  # Dependencias de docker-compose
  - package-ecosystem: "docker-compose"
    directory: "/" # raíz, donde está docker-compose.yaml
    schedule:
      interval: "weekly"

  # (Opcional) Dependencias de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # workflows en .github/workflows
    schedule:
      interval: "weekly"
