version: "3.8"

services:
  server:
    build:
      context: .
    container_name: Costa-De-Oro-Imports
    ports:
      - "${PuertoServidor}:${PuertoServidor}"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - NombreAplicacion=${NombreAplicacion}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PASSWORD_KEY_RECAPTCHA=${PASSWORD_KEY_RECAPTCHA}
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PuertoServidor}/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: "mysql:latest"
    container_name: DB-Costa-De-Oro-Imports-MySQL
    environment:
      - MYSQL_DATABASE=DB-Costa-De-Oro-Imports-MySQL
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: