use db_beer;

-- Insertar factura_proveedor
CREATE TEMPORARY TABLE temp_facturas_proveedor (
    temp_id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT,
    fecha_emision DATE,
    numero_factura VARCHAR(255)
);

SET @seq = 0;
SET @seq2 = 375;
SET @seq3 = 750;
SET @seq4 = 1125;
SET @seq5 = 1500;
SET @seq6 = 1875;
SET @seq7 = 2250;
SET @seq8 = 2625;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2104, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq := @seq + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2105, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq2 := @seq2 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2106, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq3 := @seq3 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2107, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq4 := @seq4 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2108, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq5 := @seq5 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2109, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq6 := @seq6 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2111, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq7 := @seq7 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO temp_facturas_proveedor (usuario_id, fecha_emision, numero_factura)
SELECT 2112, DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * DATEDIFF('2025-11-01', '2020-01-01')) DAY), CONCAT('FAC-', LPAD(@seq8 := @seq8 + 1, 4, '0'))
FROM (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t1
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t2
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t3
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t4
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10) as t5
CROSS JOIN (SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6) as t6
LIMIT 375;

INSERT INTO `factura_proveedor` (`activo`, `fecha_emision`, `total`, `fecha_registro`, `usuario_id`, `numero_factura`)
SELECT
    1 as activo,
    fecha_emision,
    0 as total,
    fecha_emision as fecha_registro,
    usuario_id,
    numero_factura
FROM temp_facturas_proveedor
ORDER BY fecha_emision;

DROP TEMPORARY TABLE temp_facturas_proveedor;


-- Insertar detalle_factura
CREATE TEMPORARY TABLE temp_detalles_factura (
    temp_id INT AUTO_INCREMENT PRIMARY KEY,
    factura_id BIGINT,
    producto_id BIGINT,
    cantidad INT,
    precio_compra INT,
    subtotal INT
);

INSERT INTO temp_detalles_factura (factura_id, producto_id, cantidad, precio_compra, subtotal)
SELECT
    fp.factura_id,
    p.producto_id,
    FLOOR(1 + (RAND() * 2)) as cantidad,
    CASE
        WHEN p.producto_id BETWEEN 1 AND 14 THEN FLOOR(p.precio * 0.6)
        WHEN p.producto_id BETWEEN 15 AND 22 THEN FLOOR(p.precio * 0.65)
        WHEN p.producto_id BETWEEN 23 AND 29 THEN FLOOR(p.precio * 0.7)
        WHEN p.producto_id BETWEEN 30 AND 35 THEN FLOOR(p.precio * 0.6)
        WHEN p.producto_id BETWEEN 36 AND 44 THEN FLOOR(p.precio * 0.65)
        WHEN p.producto_id BETWEEN 45 AND 50 THEN FLOOR(p.precio * 0.7)
        WHEN p.producto_id BETWEEN 51 AND 65 THEN FLOOR(p.precio * 0.55)
        WHEN p.producto_id BETWEEN 66 AND 70 THEN FLOOR(p.precio * 0.6)
        ELSE FLOOR(p.precio * 0.7)
    END as precio_compra,
    0 as subtotal
FROM factura_proveedor fp
JOIN producto p ON fp.usuario_id = p.usuario_id
CROSS JOIN (SELECT 1 as n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5) as multiples
WHERE RAND() < 0.6
GROUP BY fp.factura_id, p.producto_id  -- Esto evita duplicados
ORDER BY RAND()
LIMIT 10000;

-- Actualizar subtotales con WHERE que use KEY column
UPDATE temp_detalles_factura
SET subtotal = cantidad * precio_compra
WHERE temp_id > 0;

-- Insertar evitando duplicados que puedan existir en la tabla destino
INSERT INTO `detalle_factura` (`cantidad`, `precio_compra`, `subtotal`, `factura_id`, `producto_id`)
SELECT
    t.cantidad,
    t.precio_compra,
    t.subtotal,
    t.factura_id,
    t.producto_id
FROM temp_detalles_factura t
LEFT JOIN detalle_factura df ON t.factura_id = df.factura_id AND t.producto_id = df.producto_id
WHERE df.detalle_factura_id IS NULL;  -- Solo inserta si no existe

-- Actualizar totales en factura_proveedor
UPDATE factura_proveedor fp
JOIN (
    SELECT factura_id, SUM(subtotal) as total_calculado
    FROM detalle_factura
    GROUP BY factura_id
) as calculos ON fp.factura_id = calculos.factura_id
SET fp.total = calculos.total_calculado
WHERE fp.factura_id > 0;

DROP TEMPORARY TABLE temp_detalles_factura;